---
- hosts: all
  become: yes
  tasks:
  - name: install git on nodes
    apt:
     name: git
     state: present
  
  - name: install nginx on nodes
    apt:
     name: git
     state: present

  - name: install apache2 on nodes
    apt:
     name: apache2
     state: present
