---
- hosts: ubuntuos
  become: yes
  tasks:

    - name: Install git
      apt:
        name: git
        state: present
      tags:
        - gitpackage

    - name: Install nginx
      apt:
        name: nginx
        state: present
      tags:
        - nginxpackage

    - name: Install docker
      apt:
        name: docker.io
        state: present
      tags:
        - dockerpackage
