---
- hosts: ubuntuos
  become: yes
  tasks:
  - name: install git
    apt:
     name: git
     state: present
    tags:
    - gitpackage

  - name: install nginx
    apt:
     name: nginx
     state: present
    tags:
    - nginxpackage

  - name: install docker
    apt:
     name: docker
     state: present
    tags:
    - dockerpackage
